### ISSUE TITLE
Cannot handle classes with properties 

### ISSUE THREAD

**Issue by simkoc** [simkoc/joern#2]
```
<?php
class OpenbaySetupTest extends OpenCartSeleniumTest {
    	private $moduleInstalled = false;
}
```

Leads to:
```

Exception in thread "main" inputModules.csv.KeyedCSV.exceptions.InvalidCSVFile: While trying to handle row {start:string=50, end:string=55, type:string=PARENT_OF}: Invalid childnum 2 for start node type AST_PROP_ELEM.
	at tools.php.ast2cpg.PHPCSVEdgeInterpreter.handle(PHPCSVEdgeInterpreter.java:457)
	at inputModules.csv.csv2ast.CSV2AST.createASTEdges(CSV2AST.java:95)
	at inputModules.csv.csv2ast.CSV2AST.convert(CSV2AST.java:52)
	at inputModules.csv.csvFuncExtractor.CSVFunctionExtractor.getNextFunction(CSVFunctionExtractor.java:73)
	at tools.php.ast2cpg.Main.main(Main.java:73)
```

**Comment by simkoc** [comment]
Fixed. Was due to ast-parse introducing separate doccomment nodes instead of making it a property. Starting with version 50
